export const DEFAULT_CONFIG = {
  system: {
    name: 'institutional-solana-memecoin-bot',
    loopIntervalMs: 15_000,
    shadowMode: true,
    liveTradingEnabled: false,
    statusBroadcastIntervalMs: 300_000,
  },
  wallet: {
    encryptedKeyPath: 'storage/secrets/key.enc',
    decryptionPasswordEnv: 'KEY_ENCRYPTION_PASSWORD',
    expectedPublicKey: '',
    allowUnencryptedDevKey: false,
    devPrivateKey: '',
  },
  network: {
    rpcEndpoints: ['https://mainnet.helius-rpc.com/?api-key=REPLACE_HELIUS_KEY'],
    requestTimeoutMs: 12_000,
    failoverFailureThreshold: 3,
    failoverCooldownMs: 60_000,
    jupiterBaseUrl: 'https://lite-api.jup.ag',
    jupiterApiKey: '',
    confirmCommitment: 'confirmed',
  },
  watchlist: {
    manualFile: 'storage/watchlist/manual_tokens.json',
    scanLimit: 25,
    minLiquidityUsd: 15_000,
    minVolume24hUsd: 20_000,
    minHolders: 120,
    maxTokenAgeHours: 72,
    maxSpreadBps: 450,
    denyToken2022: true,
    denyFreezeAuthority: true,
    requireMintAuthorityRenounced: false,
    requireVerifiedToken: false,
    allowUnknownMetrics: false,
    enableDexScreener: true,
    enableBirdeye: false,
    birdeyeApiKey: '',
  },
  mrd: {
    lookbackTicks: 48,
    trendThreshold: 0.012,
    highVolatilityThreshold: 0.03,
    rangeVolatilityThreshold: 0.008,
    lowLiquidityUsd: 12_000,
  },
  strategies: {
    trendBreakoutMomentum: { enabled: true, shadow: false, baseWeight: 0.30, minConfidence: 0.58 },
    meanReversionRange: { enabled: true, shadow: false, baseWeight: 0.25, minConfidence: 0.55 },
    volatilityCompression: { enabled: true, shadow: true, baseWeight: 0.20, minConfidence: 0.60 },
    liquidityAwareConservative: { enabled: true, shadow: false, baseWeight: 0.25, minConfidence: 0.50 },
  },
  portfolio: {
    maxCandidatesPerLoop: 12,
    maxIntentsPerLoop: 3,
    minConsensusStrategies: 2,
    minAggregateConfidence: 0.62,
  },
  allocation: {
    baseCapitalSol: 5,
    reservePct: 0.30,
    maxPerTradePct: 0.08,
    maxPerStrategyPct: 0.30,
    confidenceExponent: 1.4,
  },
  risk: {
    maxOpenPositions: 4,
    maxExposurePct: 0.45,
    maxTradeSol: 0.40,
    maxDailyLossSol: 0.50,
    maxDrawdownPct: 0.20,
    maxConsecutiveLosses: 5,
    tokenCooldownMinutes: 180,
    stopLossPct: 0.20,
    takeProfitPct: 0.45,
    trailingStopPct: 0.12,
    maxPriceImpactBps: 220,
    maxInstantLossBps: 350,
    maxSlippageBps: 300,
    maxUnrealizedLossPct: 0.25,
  },
  execution: {
    baseSlippageBps: 80,
    slippageStepBps: 35,
    maxSlippageBps: 280,
    priorityFeeMicrolamportsBase: 1_500,
    priorityFeeMicrolamportsStep: 500,
    priorityFeeMicrolamportsMax: 8_000,
    maxRetries: 3,
    retryBackoffMs: 700,
    minExecutionQualityScore: 65,
    maxQuoteAgeMs: 4_000,
    minRouteLiquidityUsd: 12_000,
    quoteRateLimitMinIntervalMs: 120,
  },
  performanceGuard: {
    enabled: true,
    maxDrawdownPct: 0.20,
    pauseMinutesOnDrawdownBreach: 240,
    maxOrderFailuresInWindow: 5,
    failureWindowMinutes: 30,
    maxMedianLatencyMs: 2_000,
    minRollingEqs: 55,
  },
  governance: {
    promotionMinTrades: 25,
    promotionMinWinRate: 0.55,
    promotionMinPnlSol: 0.05,
    rollbackMaxDrawdownPct: 0.10,
    rollbackMinWinRate: 0.35,
    shadowDurationHours: 48,
  },
  telegram: {
    enabled: false,
    botToken: '',
    chatId: '',
    pollIntervalMs: 5_000,
    commandWhitelist: ['/status', '/pause', '/resume', '/shadow_on', '/shadow_off', '/emergency_stop', '/clear_emergency'],
    alerts: {
      onTrade: true,
      onRisk: true,
      onCircuitBreak: true,
    },
  },
  storage: {
    dbPath: 'storage/runtime/trading.sqlite',
    backupsDir: 'storage/backups',
    reportsDir: 'storage/reports',
    healthFile: 'storage/runtime/health.json',
    retentionDays: 14,
  },
  reports: {
    dailyReportHourUtc: 0,
  },
  features: {
    experimentalSignalFusion: false,
    experimentalSignalFusionReason: 'Disabled by default because live reliability is not yet validated over a multi-month sample.',
  },
};
